Implemented ShaderCompiler for Metal
CrossGL/visualizer pull request #39
Opened 2024-08-12 14:48 UTC by ThirulogeswarenVenkatraman

- Implemented ShaderCompiler for Vertex and Fragment Shaders
- `Common.cpp` now contains Metal Implementation
- changed `SM::Vector3` to `SM::Vector4` because simd::float3 provided by Apple has the same size as float4

```
/*! @abstract A vector of three 32-bit floating-point numbers.
   *  @description In C or Objective-C, this type is available as
   *  simd_float3. Vectors of this type are padded to have the same size and
   *  alignment as simd_float4.
*/
typedef ::simd_float3 float3;
```
Haven't touched Index and Constant Buffers, also indexed draw call

2024-08-14 12:43 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/METALCommon.h
> +    MTL::Library** library;
Do we have to use raw pointers? Can they be wrapped in some smart pointer. Similar to `ComPtr` for D3D

2024-08-14 12:44 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALConstantBuffer.h
> +        MTL::Buffer* cBuffer;
Just call this as Buffer

2024-08-14 12:44 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALIndexBuffer.h
> +        MTL::Buffer*    inxBuffer;
Rename variable as `Buffer`

2024-08-14 12:45 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALIndexBuffer.h
> +        NS::UInteger    index;
Rename of `Offset` and `Index`

2024-08-14 12:45 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALPipelineHandler.h
> +        MTL::RenderPipelineState* rpState;
Use `m_` for member variables

2024-08-14 12:47 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALPixelShader.h
> +        MTL::Library*   cSourceContent;
Struct data members should start with capital letter
`SourceContent`
`Shader`

2024-08-14 12:48 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALRenderer.cpp
> +        static constexpr std::array MTLPrimitives = {
Can we get detailed `std::array` declaration. Fill in the template params

2024-08-14 12:49 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALRenderer.cpp
> +        CompileConfig cConfig;
Can we stop adding `c` to var names unless needed?

2024-08-14 12:49 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALRenderer.cpp
> +        METALCompileObjects cObjects = {
Same here, remove `c`

2024-08-14 12:49 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALRenderer.cpp
Update variable names to not have `c` prefix

2024-08-14 12:50 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALRenderer.cpp
> +
Add a comment for now as to why this function is empty. Use `// TODO: `

2024-08-14 12:50 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALRenderer.cpp
> +}  // namespace CGL::Graphics
Remove namespace comment

2024-08-14 12:51 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALRendererImpl.h
> +    private:
Remove double `private`

2024-08-14 12:51 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALRendererImpl.h
> +        SDL_MetalView mView;
Member variables should be prefixed with `m_`

2024-08-14 12:51 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALRendererImpl.h
> +}  // namespace CGL::Graphics
Remove comment

2024-08-14 12:51 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALVertexBuffer.h
> +        MTL::Buffer*    vertexBuffer;
Rename to `Buffer` `Offset` `Index`

2024-08-14 12:52 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALVertexShader.h
> +        MTL::Library*   cSourceContent;
Remove prefix for variables

2024-08-14 12:54 UTC, ArnavMehta3000 commented on Core/Graphics/Shader/ShaderCompiler.cpp
> +        // MTL::CompileOptions* compile_options{};
Remove this comment

2024-08-14 12:55 UTC, ArnavMehta3000 commented on Core/Graphics/Shader/ShaderCompiler.cpp
> +            CGL_LOG(ShaderCompiler, Error, "Its NULL");
What is NULL here? Give more detailed log messages

2024-08-14 12:55 UTC, ArnavMehta3000 commented on Core/Graphics/Shader/ShaderCompiler.cpp
> +        result.Message = "compiled successfully";
Capitalize `Compiled`

2024-08-14 12:56 UTC, ArnavMehta3000 commented on Samples/HelloTriangle/Assets/fragment.metal
> +fragment float4 HelloTrianglePS(VertexData in [[stage_in]]) {
Can we have the brackets on separate lines pls

2024-08-19 10:38 UTC, ThirulogeswarenVenkatraman commented
@ArnavMehta3000 changes are made as per requested, also the indentation for `Renderer.h` seems to be messed, but it looks fine on my editor, also checked with other available editors

2024-08-22 20:27 UTC, ArnavMehta3000 requested changes
Other shaders (hlsl/glsl) still have float3 as their position instead of their float4. It'll be nice if you could modify other shaders as well :)

2024-08-22 20:27 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/METALCommon.h
> +    std::unique_ptr<MTL::Library*>& library;
Why are we having a reference to a unique pointer?

2024-08-22 20:27 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALPipelineHandler.cpp
> +        if(!m_rpState) {
Put bracket on next line

2024-08-22 20:27 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALPipelineHandler.h
> +        inline auto GetRenderPipelineDescriptor() const { return m_rpDescriptor; }
I'd prefer us to be a bit more explicit. Remove auto

2024-08-22 20:27 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALRenderer.cpp
> +        GetImpl()->GetMetalLayer()->setDrawableSize(
Put this on one line

2024-08-22 20:27 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALRenderer.cpp
> +        GetImpl()->GetRenderCommandEncoder()->setRenderPipelineState(
Put this all on one line

2024-08-22 20:27 UTC, ArnavMehta3000 commented on Core/Graphics/RHI/Metal/METALVertexShader.h
> +        std::unique_ptr<MTL::Library*> SourceContent;
Is this pointer to unique pointer needed?

2024-08-22 20:56 UTC, ArnavMehta3000 approved these changes

2024-08-22 20:58 UTC, merged