Working Spinning Cube Sample
CrossGL/visualizer pull request #52
Opened 2024-08-27 18:07 UTC by abhayMore

Implemented the spinning cube sample.
Added deltaTime support to ensure consistent behavior across different APIs.
Created a template class to handle vertex attributes

2024-08-27 18:09 UTC, abhayMore commented
![image](https://github.com/user-attachments/assets/334add12-4e73-4d03-bf3d-5d3bdc69777b)

2024-08-27 18:10 UTC, abhayMore commented on Core/Common.h
> +#include <cstddef>
Added these to support offsetof() and type_index

2024-08-28 10:00 UTC, ArnavMehta3000 requested changes

2024-08-28 12:06 UTC, ArnavMehta3000 approved these changes
LGTM!

2024-08-28 12:07 UTC, merged